### ISSUE TITLE
Request for TCR-AE and GMM Model

### ISSUE THREAD

**Issue by pzhang84** [ninglab/TCRPPO#1]
Hello,

I am interested in your work on TCR sequence generation and would like to explore the TCR Autoencoder (TCR-AE) and Gaussian Mixture Model (GMM) mentioned in your paper. I have looked through the repository but I couldn't find these models.

Could you please guide me to where I can find the TCR-AE and its related GMM model? If they are not currently available in this repository, would it be possible for you to share them?

Thank you in advance for your assistance.

**Comment by ziqi92** [comment]
Thank you a lot for your interest in our work!!

We do plan to share these models. I will update the well-trained TCR-AE and GMM models this week.

Best,
Ziqi

**Comment by ziqi92** [comment]
Hi,

I double-checked the repository and found that the trained autoencoder model and the gmm model have been uploaded before. 

Please check the models below:

https://github.com/ninglab/TCRPPO/blob/main/code/reward/ae_model
https://github.com/ninglab/TCRPPO/blob/main/code/reward/gmm.pkl

I'm sorry for the confusion caused and will update the README file with the description of the above files. I also noticed that the hard-coded paths for the above models in our code do not match with the above paths. I will update the code tomorrow.

Best,
Ziqi

**Comment by pzhang84** [comment]
Thanks for your quick response and pointing me out the code!
