### ISSUE TITLE
Request for TCRs dataset 

### ISSUE THREAD

**Issue by zju-wyh** [ninglab/TCRPPO#2]
Hello，
I can not find TCRs dataset on google drive(https://drive.google.com/drive/folders/1l5Pf50-7sDcKodeIo-VMHRlODu_ruGtM). It is empty. Can you upload datasets secondly?

**Comment by ziqi92** [comment]
Hi,

Thank you for letting me know! I have uploaded the datasets again. Please let me know if you have any other questions.

Best,
Ziqi

**Comment by zju-wyh** [comment]
Thanks for your quick response.
